<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get('/users', App\Livewire\Dashboard\UserIndex::class)->name(
            'users.index'
        );

        Route::get(
            '/users/create',
            App\Livewire\Dashboard\UserCreate::class
        )->name('users.create');

        Route::get(
            '/users/{user}',
            App\Livewire\Dashboard\UserEdit::class
        )->name('users.edit');

        Route::get('/leaders', App\Livewire\Dashboard\LeaderIndex::class)->name(
            'leaders.index'
        );

        Route::get(
            '/leaders/create',
            App\Livewire\Dashboard\LeaderCreate::class
        )->name('leaders.create');

        Route::get(
            '/leaders/{leader}',
            App\Livewire\Dashboard\LeaderEdit::class
        )->name('leaders.edit');

        Route::get(
            '/offline-accounts',
            App\Livewire\Dashboard\OfflineAccountIndex::class
        )->name('offline-accounts.index');

        Route::get(
            '/offline-accounts/create',
            App\Livewire\Dashboard\OfflineAccountCreate::class
        )->name('offline-accounts.create');

        Route::get(
            '/offline-accounts/{offlineAccount}',
            App\Livewire\Dashboard\OfflineAccountEdit::class
        )->name('offline-accounts.edit');

        Route::get(
            '/programs',
            App\Livewire\Dashboard\ProgramIndex::class
        )->name('programs.index');

        Route::get(
            '/programs/create',
            App\Livewire\Dashboard\ProgramCreate::class
        )->name('programs.create');

        Route::get(
            '/programs/{program}',
            App\Livewire\Dashboard\ProgramEdit::class
        )->name('programs.edit');
    });

// API
Route::prefix('/api')
    ->name('api.')
    ->group(function () {});

// Site
Route::prefix('/')->group(function () {});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function () {});
